stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - QC

# Tests for Card service

build-card-service:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Running Build"
    - cd C:\Users\schee\Documents\GitkrakenCode\Atos\kafka-prototype\CardService
    - ./mvnw install -DskipTests
    - echo "Build complete."

unit-test-card-service:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests."
    - cd C:\Users\schee\Documents\GitkrakenCode\Atos\kafka-prototype\CardService
    - ./mvnw test
    - echo "Tests complete."

sonarqube-check-card-service:
  stage: QC
  image: maven:3.8.6-jdk-11
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - cd C:\Users\schee\Documents\GitkrakenCode\Atos\kafka-prototype\CardService
    - ./mvnw verify sonar:sonar -Pcoverage
  allow_failure: true
  only:
    - develop


# Tests for Game service

build-game-service:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Running Build"
    - cd C:\Users\schee\Documents\GitkrakenCode\Atos\kafka-prototype\GameService
    - ./mvnw install -DskipTests
    - echo "Build complete."

unit-test-game-service:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests."
    - cd C:\Users\schee\Documents\GitkrakenCode\Atos\kafka-prototype\GameService
    - ./mvnw test
    - echo "Tests complete."

sonarqube-check-game-service:
  stage: QC
  image: maven:3.8.6-jdk-11
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - cd C:\Users\schee\Documents\GitkrakenCode\Atos\kafka-prototype\GameService
    - ./mvnw verify sonar:sonar -Pcoverage
  allow_failure: true
  only:
    - develop

# Tests for Lobby service

build-lobby-service:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Running Build"
    - cd C:\Users\schee\Documents\GitkrakenCode\Atos\kafka-prototype\LobbyService
    - ./mvnw install -DskipTests
    - echo "Build complete."

unit-test-lobby-service:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests."
    - cd C:\Users\schee\Documents\GitkrakenCode\Atos\kafka-prototype\LobbyService
    - ./mvnw test
    - echo "Tests complete."

sonarqube-check-lobby-service:
  stage: QC
  image: maven:3.8.6-jdk-11
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - cd C:\Users\schee\Documents\GitkrakenCode\Atos\kafka-prototype\LobbyService
    - ./mvnw verify sonar:sonar -Pcoverage
  allow_failure: true
  only:
    - develop

    # Tests for Round service

build-round-service:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Running Build"
    - cd C:\Users\schee\Documents\GitkrakenCode\Atos\kafka-prototype\RoundService
    - ./mvnw install -DskipTests
    - echo "Build complete."

unit-test-round-service:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests."
    - cd C:\Users\schee\Documents\GitkrakenCode\Atos\kafka-prototype\RoundService
    - ./mvnw test
    - echo "Tests complete."

sonarqube-check-round-service:
  stage: QC
  image: maven:3.8.6-jdk-11
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - cd C:\Users\schee\Documents\GitkrakenCode\Atos\kafka-prototype\RoundService
    - ./mvnw verify sonar:sonar -Pcoverage
  allow_failure: true
  only:
    - develop
