spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
      ## Disabling cors ¯\(°_o)/¯
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false
            max-age: 3600
      routes:
        - id: cardService-cards
          uri: ${uri.cardservice}
          predicates:
            - Path=/api/cards/**
        - id: cardService-cardSets
          uri: ${uri.cardservice}
          predicates:
            - Path=/api/cardSets/**

        - id: gameAppBff-gameappbff
          uri: ${uri.gameappbff}
          predicates:
            - Path=/api/gameappbff/**
        - id: gameAppBff-results
          uri: ${uri.gameappbff}
          predicates:
            - Path=/api/results/**

        - id: gameService
          uri: ${uri.gameservice}
          predicates:
            - Path=/api/game/**

        - id: lobbyService-lobby
          uri: ${uri.lobbyservice}
          predicates:
            - Path=/api/lobby/**

        - id: roundService-round
          uri: ${uri.roundservice}
          predicates:
            - Path=/api/round/**

        - id: gameAppBffWebsocket
          uri: ${uri.ws.gameappbff}
          predicates:
            - Path=/websocket/gameappbff/**
 
        - id: AuthenticationService-authentication
          uri: ${uri.authenticationservice}
          predicates:
            - Path=/api/gamemaster/**
    
  logging:
    level:
      root: DEBUG

front-end: http://game-app:80

uri:
  ws:
    gameappbff: ws://gameappbff:8004
  cardservice: http://card-service:8001
  gameappbff: http://gameappbff:8004
  gameservice: http://game-service:8005
  lobbyservice: http://lobby-service:8006
  roundservice: http://round-service:8002
  authenticationservice: http://authentication-service:8011
