spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
      ## Disabling cors ¯\(°_o)/¯
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false
            max-age: 3600
      routes:
        ################################## CardService
        - id: CardService-CardSet-Create
          uri: ${uri.cardservice}
          predicates:
            - Path=/cardsets/create
          filters:
            - SetPath=/api/cardsets/create

        - id: CardService-CardSet-Delete
          uri: ${uri.cardservice}
          predicates:
            - Path=/cardsets/delete
          filters:
            - SetPath=/api/cardsets/delete

        - id: CardService-CardSet-Update
          uri: ${uri.cardservice}
          predicates:
            - Path=/cardsets/update
          filters:
            - SetPath=/api/cardsets/update

        - id: CardService-Cards-Create
          uri: ${uri.cardservice}
          predicates:
            - Path=/cards/create
          filters:
            - SetPath=/api/cards/create

        - id: CardService-Cards-Delete
          uri: ${uri.cardservice}
          predicates:
            - Path=/cards/delete
          filters:
            - SetPath=/api/cards/delete

        - id: CardService-Cards-update
          uri: ${uri.cardservice}
          predicates:
            - Path=/cards/seed
          filters:
            - SetPath=/api/cards/seed

        - id: CardService-Cards-update
          uri: ${uri.cardservice}
          predicates:
            - Path=/cards/update
          filters:
            - SetPath=/api/cards/update

        ################################## GameAppBff
        - id: GameAppBff-cardsets
          uri: ${uri.gameappbff}
          predicates:
            - Path=/gameappbff/cardSets/{segment}
          filters:
            - SetPath=/api/gameappbff/cardSets/{segment}

        - id: GameAppBff-lobby
          uri: ${uri.gameappbff}
          predicates:
            - Path=/gameappbff/lobby
          filters:
            - SetPath=/api/gameappbff/lobby

        - id: GameAppBff-game
          uri: ${uri.gameappbff}
          predicates:
            - Path=/gameappbff/game/{segment}
          filters:
            - SetPath=/api/gameappbff/game/{segment}

        - id: GameAppBff-games
          uri: ${uri.gameappbff}
          predicates:
            - Path=/gameappbff/games
          filters:
            - SetPath=/api/gameappbff/games

        - id: GameAppBff-results
          uri: ${uri.gameappbff}
          predicates:
            - Path=/results/phase3?{segment}
          filters:
            - SetPath=/api/results/phase3?{segment}

        - id: GameAppBff-results-individual
          uri: ${uri.gameappbff}
          predicates:
            - Path=/results/phase3individual?{segment}
          filters:
            - SetPath=/api/results/phase3individual?{segment}

        ################################## GameService
        - id: GameService-create
          uri: ${uri.gameservice}
          predicates:
            - Path=/game/create
          filters:
            - SetPath=/api/game/create

        - id: GameService-end
          uri: ${uri.gameservice}
          predicates:
            - Path=/game/end/{segment}
          filters:
            - SetPath=/api/game/end/{segment}

        - id: GameService-start
          uri: ${uri.gameservice}
          predicates:
            - Path=/game/start/{segment}
          filters:
            - SetPath=/api/game/start/{segment}

        - id: GameService-abort
          uri: ${uri.gameservice}
          predicates:
            - Path=/game/abort/{segment}
          filters:
            - SetPath=/api/game/abort/{segment}

        ################################## LobbyService
        - id: LobbyService-join
          uri: ${uri.lobbyservice}
          predicates:
            - Path=/lobby/join
          filters:
            - SetPath=/api/lobby/join

        - id: LobbyService-quit
          uri: ${uri.lobbyservice}
          predicates:
            - Path=/lobby/quit
          filters:
            - SetPath=/api/lobby/quit

        ################################## RoundService
        - id: RoundService-dislike
          uri: ${uri.roundservice}
          predicates:
            - Path=/round/dislikeCard
          filters:
            - SetPath=/api/round/dislikeCard

        - id: RoundService-like
          uri: ${uri.roundservice}
          predicates:
            - Path=/round/likeCard
          filters:
            - SetPath=/api/round/likeCard

        - id: RoundService-select
          uri: ${uri.roundservice}
          predicates:
            - Path=/round/selectCards
          filters:
            - SetPath=/api/round/selectCards

        - id: RoundService-startnextround
          uri: ${uri.roundservice}
          predicates:
            - Path=/round/startnextround
          filters:
            - SetPath=/api/round/startnextround
  logging:
    level:
      root: DEBUG

uri:
  cardservice: http://card-service:8001
  gameappbff: http://gameappbff:8004
  gameservice: http://game-service:8005
  lobbyservice: http://lobby-service:8006
  roundservice: http://round-service:8002
