spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
      ## Disabling cors ¯\(°_o)/¯
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false
            max-age: 3600
      routes:
        - id: cardService-cards
          uri: ${URI_CARDSERVICE:http://card-service:8001}
          predicates:
            - Path=/api/cards/**
        - id: cardService-cardSets
          uri: ${URI_CARDSERVICE:http://card-service:8001}
          predicates:
            - Path=/api/cardSets/**
        - id: gameAppBff-gameappbff
          uri: ${URI_GAMEAPPBFF:http://gameappbff:8004}
          predicates:
            - Path=/api/gameappbff/**
        - id: gameAppBff-results
          uri: ${URI_GAMEAPPBFF:http://gameappbff:8004}
          predicates:
            - Path=/api/results/**
        - id: gameService
          uri: ${URI_GAMESERVICE:http://game-service:8005}
          predicates:
            - Path=/api/game/**
        - id: lobbyService-lobby
          uri: ${URI_LOBBYSERVICE:http://lobby-service:8006}
          predicates:
            - Path=/api/lobby/**
        - id: roundService-round
          uri: ${URI_ROUNDSERVICE:http://round-service:8002}
          predicates:
            - Path=/api/round/**
        - id: gameAppBffWebsocket
          uri: ${URI_WS_GAMEAPPBFF:ws://gameappbff:8004}
          predicates:
            - Path=/websocket/gameappbff/**
  logging:
    level:
      root: DEBUG
