httpOrHttps: http

server:
  port: 8010
spring:
  profiles:
    active: production
  cloud:
    gateway:
      routes:
        - id: cardService
          uri: ${httpOrHttps}://localhost:8001
          predicates:
            - Path=/api/cards/**
            - Path=/api/cardsets/**
        - id: gameService
          uri: ${httpOrHttps}://localhost:8005
          predicates:
              - Path=/api/game/**
        - id: lobbyService
          uri: ${httpOrHttps}://localhost:8006
          predicates:
              - Path=/api/lobby/**
        - id: roundServiceWebsocket
          uri: ws://localhost:8007
          predicates:
            - Path=/websocket/roundservice
        - id: gameAppBffWebsocket
          uri: ws://localhost:8004
          predicates:
              - Path=/websocket/gameappbff
        - id: adminAppBff
          uri: ${httpOrHttps}://localhost:8007
          predicates:
              - Path=/api/adminappbff/**
        - id: frontend
          uri: ${httpOrHttps}://localhost:3001
          predicates:
            - Path=/**