spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
      ## Disabling cors ¯\(°_o)/¯
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false
            max-age: 3600
      routes:
        - id: cardService-cards
          uri: ${uri.cardservice}
          predicates:
            - Path=/api/cards/**
        - id: cardService-cardSets
          uri: ${uri.cardservice}
          predicates:
            - Path=/api/cardSets/**

        - id: gameAppBff-gameappbff
          uri: ${uri.gameappbff}
          predicates:
            - Path=/api/gameappbff/**
        - id: gameAppBff-results
          uri: ${uri.gameappbff}
          predicates:
            - Path=/api/results/**

        - id: gameService
          uri: ${uri.gameservice}
          predicates:
            - Path=/api/game/**

        - id: lobbyService-lobby
          uri: ${uri.lobbyservice}
          predicates:
            - Path=/api/lobby/**

        - id: roundService-round
          uri: ${uri.roundservice}
          predicates:
            - Path=/api/round/**

        - id: gameMasterService-gamemaster
          uri: ${uri.gamemasterservice}
          predicates:
            - Path=/api/gamemaster/**

        - id: gameAppBffWebsocket
          uri: ${uri.ws.gameappbff}
          predicates:
            - Path=/websocket/gameappbff/**
  logging:
    level:
      root: DEBUG

front-end: http://localhost:3001

uri:
  ws:
    gameappbff: ws://localhost:8004
  cardservice: http://localhost:8001
  gameappbff: http://localhost:8004
  gameservice: http://localhost:8005
  lobbyservice: http://localhost:8006
  roundservice: http://localhost:8002
