server:
  port: 8010
spring:
  cloud:
    gateway:
      routes:
        - id: cardService
          uri: http://localhost:8001
          predicates:
            - Path=/api/cards/**
            - Path=/api/cardsets/**
        - id: gameService
          uri: http://localhost:8005
          predicates:
              - Path=/api/game/**
        - id: lobbyService
          uri: http://localhost:8006
          predicates:
              - Path=/api/lobby/**
        - id: roundServiceWebsocket
          uri: ws://localhost:8007
          predicates:
            - Path=/websocket/roundservice
        - id: gameAppBffWebsocket
          uri: ws://localhost:8004
          predicates:
              - Path=/websocket/gameappbff
        - id: adminAppBff
          uri: http://localhost:8007
          predicates:
              - Path=/api/adminappbff/**