name: SonarCloud analysis

on:
  push:
    branches: [ "main", "development", "kubernetes-test" ]
  pull_request:
    branches: [ "main", "development" ]
  workflow_dispatch:

jobs:
  SonarCloud:
    permissions:
      pull-requests: read
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey= ${{ secrets.SONAR_CLOUD_PROJECT_KEY }}
            -Dsonar.organization= ${{ secrets.SONAR_ORGANIZATION }}
          projectBaseDir: ..
