name: SonarCloud analysis

on:
  push:
    branches: [ "main", "development", "kubernetes-test" ]
  pull_request:
    branches: [ "main", "development" ]
  workflow_dispatch:

jobs:
  sonarcloud-check-Cardservice:
    permissions:
      pull-requests: read
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd CardService
          mvn verify sonar:sonar \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.SONAR_CLOUD_PROJECT_KEY }} \
