apiVersion: apps/v1
kind: Deployment
metadata:
  name: eviden-authentication-service-deployment
  labels:
    app: eviden-authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eviden-authentication-service
  template:
    metadata:
      labels:
        app: eviden-authentication-service
    spec:
      containers:
        - name: eviden-authentication-service
          image: europe-west4-docker.pkg.dev/vocal-invention-443612-d9/docker-images/eviden-back-end-authentication-service:kubernetes-test
          ports:
            - containerPort: 8011
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: dbname
            - name: DB_HOST
              value: "localhost"
            - name: DB_PORT
              value: "3311"
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.1
          args:
            - "--structured-logs"
            - "--port=3311"
            - "vocal-invention-443612-d9:europe-west4:authentication-db"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: service-account
              mountPath: /secrets/cloudsql
              readOnly: true

      volumes:
        - name: service-account
          secret:
            secretName: service-account-secret
        - name: my-secrets-volume
          secret:
            secretName: cloudsql-instance-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service-service
spec:
  selector:
    app: eviden-authentication-service
  ports:
    - protocol: TCP
      port: 8011
      targetPort: 8011
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-sql-proxy-service
spec:
  selector:
    app: eviden-authentication-service
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3311


