apiVersion: apps/v1
kind: Deployment
metadata:
  name: eviden-authentication-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eviden-authentication-service-deployment
  template:
    metadata:
      labels:
        app: eviden-authentication-service-deployment
    spec:
      containers:
        - name: eviden-authentication-service
          image: europe-west4-docker.pkg.dev/protean-bit-441008-h3/docker-hub/eviden-back-end-authentication-service
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://cloud-sql-proxy-auth:3306/gamemaster_db"
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: "my-cluster-kafka-bootstrap:9092"
            - name: SPRING_JPA_HIBERNATE_DDL-AUTO
              value: "update"
          ports:
            - containerPort: 8011
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8111
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8111
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.0
          command:
            - /cloud_sql_proxy
            - -dir=/cloudsql
            - -instances=your-project-id:your-region:your-instance-id
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
        - name: cloudsql
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service-service
spec:
  selector:
    app: eviden-authentication-service-deployment
  ports:
    - protocol: TCP
      port: 8011
      targetPort: 8011
