apiVersion: apps/v1
kind: Deployment
metadata:
  name: eviden-authentication-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eviden-authentication-service-deployment
  template:
    metadata:
      labels:
        app: eviden-authentication-service-deployment
    spec:
      containers:
        - name: eviden-authentication-service
          image: europe-west4-docker.pkg.dev/vocal-invention-443612-d9/docker-images/eviden-back-end-authentication-service:kubernetes-test
          env:
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: "kafka:9092"
            - name: SPRING_JPA_HIBERNATE_DDL-AUTO
              value: "update"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: dbname
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: host
          ports:
            - containerPort: 8011
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8011
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8011
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi" # Reduce to a lower value
              cpu: "250m"
            limits:
              memory: "512Mi" # Reduce if not necessary
              cpu: "500m"
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.28.1
          command: [ "/cloud_sql_proxy",
                     "-instances=vocal-invention-443612-d9:europe-west4:authentication-db=tcp:3306",
                     "-credential_file=/secrets/cloudsql/sql_credentials.json" ]
          volumeMounts:
            - name: my-secrets-volume
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: my-secrets-volume
          secret:
            secretName: cloudsql-instance-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service-service
spec:
  selector:
    app: eviden-authentication-service-deployment
  ports:
    - protocol: TCP
      port: 8011
      targetPort: 8011
