apiVersion: apps/v1
kind: Deployment
metadata:
  name: eviden-authentication-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eviden-authentication-service-deployment
  template:
    metadata:
      labels:
        app: eviden-authentication-service-deployment
    spec:
      containers:
        - name: eviden-authentication-service
          image: i486205/eviden-authentication-service:development
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://eviden-auth-service-db/authentication_db"
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: "my-cluster-kafka-bootstrap:9092"
            - name: SPRING_JPA_HIBERNATE_DDL-AUTO
              value: "update"
          ports:
            - containerPort: 8011
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8111
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8111
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service-service
spec:
  selector:
    app: eviden-authentication-service-deployment
  ports:
    - protocol: TCP
      port: 8011
      targetPort: 8011
